CREATE TABLE IF NOT EXISTS users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS requests (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    solicitant_name VARCHAR(255) NOT NULL,
    request_date TIMESTAMP NOT NULL,
    subject_consult VARCHAR(255) NOT NULL,
    description_consult VARCHAR(255) NOT NULL
);